### PR TITLE
fixed time grid to not error when valid values are given

### LINKED ISSUE #182: Manually specifying time_grid results in an error
Manually specifying time_grid results in an error:

```
DataLongitudinal(
        data = dat_lm,
        formula = sld ~ time,
        subject = "pt",
        threshold = 5,
        time_grid = c(2, 4)
    )

Error in is.sorted(object@time_grid) : 
  could not find function "is.sorted"
```

### PR DESCRIPTION
**Pull request by gowerc**
Closes #182

### CODE REVIEW

File: tests/testthat/test-DataLongitudinal.R [hunk 1]
```diff
@@ -27,3 +25,51 @@ test_that("DataLongitudinal being rendered to list is as expected for simple inp
...
+
+test_that("time_grid is rejected if in an invalid format", {
+    x <- data.frame(
+        vpt = c("b", "a", "a", "b", "c", "a"),
+        vtime = c(10, 20, 15, 5, 25, 35),
+        voutcome = c(2, 1, 4, 5, 6, 2)
+    )
+
+    # First check that it doesn't error when used properly
+    result <- tryCatch(
```
Comment (danielinteractive) [inline tests/testthat/test-DataLongitudinal.R:38]: Why is this needed? Would `expect_silent` be simpler?

File: tests/testthat/test-DataSurvival.R [hunk 2]
```diff
@@ -57,3 +57,59 @@ test_that("DataSurvival being rendered to list is as expected for simple inputs"
...
+    x2 <- data.frame(
+        vpt = c("b", "a", "c"),
+        varm = c("a", "a", "a"),
+        vstudy = c("s1", "s1", "s1"),
+        vtime = c(10, 20, 30),
+        vevent = c(1, 1, 1)
+    )
+
+    # First check that it doesn't error when used properly
+    result <- tryCatch(
```
Comment (danielinteractive) [inline tests/testthat/test-DataSurvival.R:76]: Same here?

File: tests/testthat/test-DataLongitudinal.R (hunk 1 above)
Comment (danielinteractive) [reply tests/testthat/test-DataLongitudinal.R:38]: I guess normally we want the error from the test then, not just whether it errored. and since you fix it now logs are clean.
