### PR TITLE
140: Fix LongitudinalGSF 

### LINKED ISSUE #140: Error with LongitudinalGSF and 1 study
When using logitudinal model `LongitudinalGSF`, I get the error and no sampling is possible.
```
Chain 1 Unrecoverable error evaluating the log probability at the initial value. 
Chain 1 Exception: mismatch in number dimensions declared and found in context; processing stage=parameter initialization; variable name=lm_gsf_mu_bsld; dims declared=(1); dims found=() (in '/var/folders/q5/j352n9454xg4cx3q5zm06vq00000gn/T/RtmpMYJucf/model-7d731b0f7605.stan', line 298, column 4 to column 54) 
```

Reprex:
```r
## Generate Test data with known parameters
jlist <- simulate_joint_data(
    n_arm = c(500, 500),
    times = 1:2000,
    lambda_cen = 1 / 9000,
    beta_cat = c(
        "A" = 0,
        "B" = -0.1,
        "C" = 0.5
    ),
    beta_cont = 0.3,
    lm_fun = sim_lm_random_slope(
        intercept = 30,
        slope_mu = c(1, 2),
        slope_sigma = 0.2,
        sigma = 3,
        phi = 0.1
    ),
    os_fun = sim_os_weibull(
        lambda = 0.00333,  # 1/300
        gamma = 0.97
    )
)

## Extract data to individual datasets, reduce longitudinal data to specific time points
dat_os <- jlist$os
dat_lm <- jlist$lm |>
    dplyr::filter(time %in% c(1, 50, 100, 150, 200, 250, 300)) |>
    dplyr::arrange(time, pt)



## Specify required variables to fit the model to within our dataset
jdat <- DataJoint(
    survival = DataSurvival(
        data = dat_os,
        formula = Surv(time, event) ~ cov_cat + cov_cont,
        subject = "pt",
        arm = "arm",
        study = "study"
    ),
    longitudinal = DataLongitudinal(
        data = dat_lm,
        formula = sld ~ time,
        subject = "pt",
        threshold = 5
    )
)

jm <- JointModel(
    link = LinkNone(),
    longitudinal = LongitudinalGSF(),
    survival = SurvivalWeibullPH()
)

## Sample from JointModel
mp <- sampleStanModel(
    jm,
    data = jdat,
    iter_sampling = 500,
    iter_warmup = 500,
    chains = 1,
    parallel_chains = 1,
    exe_file = file.path("local", "full")
)

```

If I assigned some patients to Study-2 (and arm=Group-3), the model "works" but gives another error related to initial values, which I think is an unrelated issue.
```r
## Works with more studies -----

## Extract data to individual datasets, reduce longitudinal data to specific time points
dat_os <- jlist$os
dat_os$study <- as.character(dat_os$study)
dat_os$arm <- as.character(dat_os$arm)
dat_os[1:20, ]$study <- "Study-2"
dat_os[1:20, ]$arm <- "Group-3"

dat_lm_3 <- jlist$lm |> dplyr::filter(time %in% c(1, 50, 100, 150, 200, 250, 300))
dat_lm_3$study <- as.character(dat_lm_3$study)
dat_lm_3$arm <- as.character(dat_lm_3$arm)
dat_lm_3[1:140, ]$study <- "Study-2"
dat_lm_3[1:140, ]$arm <- "Group-3"

dat_lm <- dat_lm_3 |> dplyr::arrange(time, pt)


## Specify required variables to fit the model to within our dataset
jdat <- DataJoint(
    survival = DataSurvival(
        data = dat_os,
        formula = Surv(time, event) ~ cov_cat + cov_cont,
        subject = "pt",
        arm = "arm",
        study = "study"
    ),
    longitudinal = DataLongitudinal(
        data = dat_lm,
        formula = sld ~ time,
        subject = "pt",
        threshold = 5
    )
)


jm <- JointModel(
    link = LinkNone(),
    longitudinal = LongitudinalGSF(),
    survival = SurvivalWeibullPH()
)


## Sample from JointModel
mp <- sampleStanModel(
    jm,
    data = jdat,
    iter_sampling = 500,
    iter_warmup = 500,
    chains = 1,
    parallel_chains = 1,
    exe_file = file.path("local", "full")
)
```

### PR DESCRIPTION
**Pull request by danielinteractive**
closes #140

- adds `array` flag to each size so even single numbers will be passed as array when needed
- fixes initial values for `LongitudinalGSF` model
- fixes `link_gsf_dsld` default argument
- adds regression test for `LongitudinalGSF` sampling

### CODE REVIEW

File: R/LongitudinalGSF.R [hunk 1]
```diff
@@ -36,14 +36,14 @@ NULL
 #' @export
 LongitudinalGSF <- function(
     mu_bsld = prior_lognormal(log(55), 5, init = 55),
-    mu_ks = prior_lognormal(0, 0.5, init = 0),
-    mu_kg = prior_lognormal(-0.36, 1, init = -0.36),
+    mu_ks = prior_lognormal(0, 0.5, init = 0.01),
+    mu_kg = prior_lognormal(-0.36, 1, init = 0.01),
```
Comment (gravesti) [inline R/LongitudinalGSF.R:40]: These initial values put them in the boundaries of the stan code, but I wonder if we should use the same construction as for `mu_bsld` by specifying the mean as a `log()` (or `init` as `exp()`) for clarity.

**Review by gravesti — DISMISSED** [review]
Looks good to me @danielinteractive 
Just one comment about initial values, but we can also update that later as necessary.

File: R/LongitudinalGSF.R (hunk 1 above)
Comment (danielinteractive) [reply R/LongitudinalGSF.R]: Sounds good, thanks @gravesti

**Review by gravesti — APPROVED** [review]
